FROM node:22-alpine AS build

WORKDIR /app

COPY hato-fe/package.json hato-fe/package-lock.json ./
RUN npm ci

COPY hato-fe/ ./

RUN npm run build -- --configuration development --output-path=dist/docker

FROM nginx:1.27-alpine

COPY infraestructure/dev/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/docker/browser /usr/share/nginx/html

EXPOSE 80
